### ISSUE TITLE
Masalah install

### ISSUE THREAD

**Issue by mol3x** [jokogendeng77/SHPxBOT#5]
Bang kok ga bisa di clone yah terus kalo download manual di npm install error terus

**Comment by jokogendeng77** [comment]
pake installer yang ada aja

**Comment by fery997** [comment]
bang ada wa yg bisa dihubungi ngga , sya mau belajar

**Comment by jokogendeng77** [comment]
**https://chat.whatsapp.com/CrXzuvGr9UI2wfAOFQNt4n**
