### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by punjasin** [jokogendeng77/SHPxBOT#7]
seem like it need licence file i have add discord but no one answer this ?

**Comment by oyi77** [comment]
yes it needs license file, you could contact the discord. after doing the
deposits to the mentioned address shown in the CLI screen

**Comment by punjasin** [comment]
i have deposit to address pleased answer my discord or telegram

**Comment by jokogendeng77** [comment]
okey will check it

**Comment by punjasin** [comment]
please let me know since i got no response here :(
